### ISSUE TITLE
Testimonials submission form

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/testimonials#62]
Is this a viable enhancement?

**Comment by RiaanKnoetze** [comment]
Just to add a quick note: the decent form builder plugins should already make allowance for this by connecting front end posting to custom post types (e.g. https://ninjaforms.com/extensions/front-end-posting/).

**Comment by jeffikus** [comment]
thanks @RiaanKnoetze - good point ;) this is on hold for now though :)

**Comment by RiaanKnoetze** [comment]
@jeffikus - Pretty sure this won't be included any time soon. Shouldn't we just close the issue?

**Comment by jeffikus** [comment]
@RiaanKnoetze in theory yes. but leaving it open for in case anyone wants to tackle it.
