### ISSUE TITLE
Testimonials by Woothemes vs Jetpack Testimonials

### ISSUE THREAD

**Issue by bhubbard** [woocommerce/testimonials#69]
Hey guys,

Since Woothemes has now joined Automatic, I was wondering if there were any thoughts as far as possibility of merging the testimonials plugin completely into the Jetpack Testimonials or doing the reverse? Since the Jetpack testimonials doesn't do much other then create the cpt, I think it might make sense to move this testimonial plugin features into the jetpack plugin. Thoughts?

**Comment by jameskoster** [comment]
The relationship between Jetpack testimonials and our own testimonials plugin (and our Projects plugin / the Jetpack portfolio module) are on the radar.
